config/routes.rb
Rails.application.routes.draw do

  root 'toppages#index'
  devise_for :users
  resources 'requests'  
  resources 'messages'
end

app/models/request.rb
class Request < ApplicationRecord
    include Statesman::Adapters::ActiveRecordQueries
    
    validates :user_id, presence: true
    validates :title, presence: true
    validates :budget, presence: true
    validates :description, presence: true
    
    belongs_to :user
    has_many :commodities
    accepts_nested_attributes_for :commodities
    mount_uploader :image, ImageUploader
    
    has_many :request_transitions, autosave: false

  def state_machine
    @state_machine ||= RequestStateMachine.new(self, transition_class: RequestTransition)
  end

  def self.transition_class
    RequestTransition
  end

  def self.initial_state
    :raised
  end

  has_many :transitions, class_name: "RequestTransition", autosave: false

  # Initialize the state machine
  def state_machine
    @state_machine ||= RequestStateMachine.new(self, transition_class: RequestTransition,
                                                   association_name: :transitions)
  end

  # Optionally delegate some methods
  delegate :can_transition_to?, :transition_to!, :transition_to, :current_state,
           to: :state_machine 
 
  private_class_method :initial_state
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  def index
    @requests = Request.all
  end
  
  def show
    @request = Request.find(params[:id])
  end
  
  def new
    @request = Request.new
    @request.commodities.build
  end
  
  def create
    @request = current_user.requests.new(request_params)
    if @request.save
      redirect_to root_path, notice: '投稿に成功しました'
    else
      logger.debug('エラー内容は下記です')
      logger.debug(@request.commodities.inspect)
      logger.debug(@request.errors.messages)
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end
  
  private
  def request_params
    params.require(:request).permit(:title, :budget, :description, commodities_attributes: [:id, :product_name, :amount, :price, :image],)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/index.html.erb
<div class="request-index-wrapper">
    <div class="request-index-container">
        <% @requests.each do |request| %>
            <div class="row">
                <div class="col-md-offset-2 col-md-6">
                    <div class="request-index-single">
                        <h2 class="request-index-text">件名：<%= request.title %></h2>
                        <h2 class="request-index-text">予算：<%= request.budget %></h2>
                        <h2 class="request-index-text">詳細：<%= request.description %></h2>
                    </div>
                    <div class="col-md-2">
                        <%= link_to "詳細を見る", request %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/requests/new.html.erb
<div class="request-new-wrapper">
    <div class="request-new-container">
        <div class="row">
            <div class="col-md-offset-4 col-md-4">
                <h2>リクエスト投稿</h2>
                <%= form_for @request do |f| %>
                <div class="form-group">
                    <%= f.label :title, class: "text-white" %>
                    <%= f.text_field :title, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :budget, class: "text-white" %>
                    <%= f.text_field :budget, class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= f.label :description, class: "text-white" %>
                    <%= f.text_field :description, class: "form-control" %>
                </div>
             </div>       
                     
                    <table class="table table-striped table-boarded">
                        <tbody>
                            <tr>
                                <th class="text-center">product name</th>
                                <th class="text-center">amount</th>
                                <th class="text-center">unit price</th>
                                <th class="text-center">sample image</th>
                            </tr>
                        <%= f.nested_fields_for :commodities, wrapper_tag: :tr do |c| %>
                            <td>
                            <div class="form-group">
                                <%= c.text_field :product_name, class: "form-control" %>
                            </div>
                            </td>
                            <td>
                            <div class="form-group">
                                <%= c.text_field :amount, class: "form-control" %>
                            </div>
                            </td>
                            <td>
                            <div class="form-group">
                                <%= c.text_field :price, class: "form-control" %>
                            </div>
                            </td>
                            <td>
                            <div class="form-group">
                                <%= c.file_field :image %>
                            </div>
                            </td>
                            <td><%= c.remove_nested_fields_link 'Delete', class: 'btn　btn-danger', role: 'button' %></td>
                        <% end %>
                        </tbody>
                    </table>
                    <%= f.add_nested_fields_link :commodities, 'Add new', class:'btn btn-primary', role: 'button' %>
                <div class="form-group">
                    <%= f.submit "投稿", class: 'btn-block btn-white' %>
                </div>    
                <% end %>
            
        </div>
    </div>
</div>

app/views/requests/show.html.erb
<div class="request-show-wrapper">
    <div class="request-show-container">
        <div class="row">
            <div class="col-md-offset-3 col-md-6">
                <%= @request.title %>
                <%= @request.budget %>
                <%= @request.description %>
                
                <% @request.commodities.each do |commodity| %>
                <%= commodity.product_name %>
                <%= image_tag commodity.image.url %>
                <% end %>
                <%= link_to 'メッセージを投稿者に送る', new_message_path(request_id: @request.id) %>
            </div>
            <div class="col-md-offset-4 col-md-4">
                
            </div>
        </div>
    </div>
</div>