config/routes.rb
Rails.application.routes.draw do

  root 'toppages#index'
  devise_for :users
  resources 'requests'  
  resources 'messages'
end

app/views/layouts/_navbar_buyer.html.erb
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
        <div class="container">
          <%= link_to root_path do %>
            <span><%= image_tag 'icons/logo.png', class: 'navbar-brand' %></span>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to new_request_path do %>
                  <%= image_tag 'icons/request_post.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to '#' do %>
                  <%= image_tag 'icons/request_status.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <%= image_tag 'icons/logout.png' %>
                <% end %>
              </li>
          </ul>
        </div>
      </nav>

app/views/layouts/_navbar_seller.html.erb
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
        <div class="container">
          <%= link_to root_path do %>
            <span><%= image_tag 'icons/logo.png', class: 'navbar-brand' %></span>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to requests_path do %>
                  <%= image_tag 'icons/requests_index.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to '#' do %>
                  <%= image_tag 'icons/request_status.png' %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <%= image_tag 'icons/logout.png' %>
                <% end %>
              </li>
          </ul>
        </div>
     </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bakugai</title>
    <%= csrf_meta_tags %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
     <script type="text/javascript">
     $(function(){
    var nowchecked = $('input[type=radio]#buyer:checked').val();
    $('input[type=radio]#buyer').click(function(){
        if($(this).val() == nowchecked) {
            $(this).prop('checked', false);
            nowchecked = false;
        } else {
            nowchecked = $(this).val();
        }
      });
    });
    </script>
    
     <script type="text/javascript">
     $(function(){
    var nowchecked = $('input[type=radio]#seller:checked').val();
    $('input[type=radio]#seller').click(function(){
        if($(this).val() == nowchecked) {
            $(this).prop('checked', false);
            nowchecked = false;
        } else {
            nowchecked = $(this).val();
        }
      });
    });
    </script>
  
  </head>

  <body>

      <% if user_signed_in? && current_user.roles.where(name: 'buyer').present? %>
          <%= render 'layouts/navbar_buyer' %>
      <% elsif user_signed_in? && current_user.roles.where(name: 'seller').present? %>
          <%= render 'layouts/navbar_seller' %>
      <% else %>
        <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
            <div class="container">
              <%= link_to root_path do %>
                <span><%= image_tag 'icons/logo.png', class: 'navbar-brand' %></span>
              <% end %>
              <ul class="nav navbar-nav navbar-right">
                  <li>
                    <%= link_to new_user_registration_path do %>
                      <%= image_tag 'icons/register.png' %>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_user_session_path do %>
                      <%= image_tag 'icons/login.png' %>
                    <% end %>
                  </li>
                
              </ul>
            </div>
       </nav>
      <% end %>
      
  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>
    
    <%= yield %>
  </body>
</html>